version: '3.7'
services:
    redsos-app:
        build: ../../../Dockerfile
        image: trinity-dev/redsos-services:1.0
        environment:
            - JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=production
            - SPRING_DATASOURCE_URL=bolt://127.0.0.1:7687
            - JHIPSTER_SLEEP=10
            - NEO4J_USER=neo4j
            - NEO4J_PASSWORD=n304J
            - GOOGLE_APPLICATION_CREDENTIALS=/home/redsos/config/service-account-file.json
            - GOOGLE_DATABASE_URL=https://redsos-2020.firebaseio.com
        ports:
            - 8082:8082
        networks:
          redsos-external:
networks:
  redsos-external:
      driver: bridge