---
spring:
  profiles: test # test server configuration
  data:
    neo4j:
      username: ${REDSOS_USERNAME:neo4j}
      password: ${REDSOS_PASSWORD:admin}
      uri: ${REDSOS_DATASOURCE_URL:bolt://localhost:7687}

