server:
    servlet:
      context-path: /com.trinity.dev.redsos
    port: 8082
spring:
  profiles.active: developer # test server configuration
  application: 
    name: com.trinity.dev.agora
  jmx:
    default-server: com.trinity.dev.redsos
#  main:
#    allow-bean-definition-overriding: true:
google:
  application:
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS:resources/service-account-file.json}
  database:
    url: ${https://redsos-2020.firebaseio.com}
