version: '3.7'
services:
    redsos-app:
        container_name: redsos-services
        build: .
        image: trinity-dev/redsos-services:1.2
        environment:
            - JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=developer
            - REDSOS_DATASOURCE_URL=bolt://172.20.0.2:7687
            - JHIPSTER_SLEEP=10
            - REDSOS_USERNAME=neo4j
            - REDSOS_PASSWORD=admin
            - GOOGLE_APPLICATION_CREDENTIALS=/home/redsos/config/service-account-file.json
            - GOOGLE_DATABASE_URL=https://redsos-2020.firebaseio.com
        ports:
            - 8082:8082
        network_mode:
            redsos-network