 
pipeline {
    agent any
    stages {
        stage('Build') {
		    steps {
                echo "mvn --version"
                echo "Build"
            }
	    }
	    stage('Test') {
		   steps {
                echo "Test"
           }
	    }
    }
}