version: '3.7'
services:
    redsos-neo4j:
        container_name: neo4j
        image: neo4j:3.5.8
        restart: always
        volumes:
            - neo4j
            - ${HOME}/neo4j/data:/data
            - ${HOME}/neo4j/logs:/logs
        ports:
            - 7688:7687
            - 17474:7474